version: '3.5'

services:
  uniph-postgres:
    container_name: local-postgres
    image: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD:-12345678}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_DB: uniph_db
    volumes:
      - /home/danilosp/Documentos/Danilo SIlva/development/contaneirs/postgresql:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    networks:
        - postgres-compose-network
    restart: unless-stopped

  uniph-pgadmin4:
    container_name: local-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-danilo@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - /home/danilosp/Documentos/Danilo SIlva/development/contaneirs/pgadmin4:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres-compose-network
    restart: unless-stopped

networks:
  postgres-compose-network:
    driver: bridge