spring:
  application:
    name: uniph-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:${datasource.url:jdbc:postgresql://${DATASOURCE_SERVER:${datasource.server:""}}:${DATASOURCE_PORT:${datasource.port:5432}}/${DATASOURCE_DATABASE:${datasource.database:""}}}}
    username: ${DATASOURCE_USERNAME:${database.username:""}}
    password: ${DATASOURCE_PASSWORD:${database.password:""}}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.naming:
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob.non_contextual_creation: true
    show-sql: ${SHOW_SQL:true}

  liquibase:
    change-log: classpath:changelog-master.yaml

  jackson:
    date-format: yyyy-MM-dd
    deserialization.fail-on-unknown-properties: true

server:
  port: ${SERVER_PORT:8081}